---
AWSTemplateFormatVersion: '2010-09-09'
Resources:

  SimpleScalingUp:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: "ChangeInCapacity"
      PolicyType: "SimpleScaling"
      Cooldown: "480"
      AutoScalingGroupName:
        Fn::ImportValue: ASG
      ScalingAdjustment: 1

  MemoryReservationHighAlert:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Maximum
      Threshold: 80
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
      Period: '60'
      AlarmActions:
      - Ref: SimpleScalingUp
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value:
          Fn::ImportValue: ECScluster
      ComparisonOperator: GreaterThanThreshold
      MetricName: MemoryReservation

  SimpleScalingDown:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: "ChangeInCapacity"
      PolicyType: "SimpleScaling"
      Cooldown: "480"
      AutoScalingGroupName:
        Fn::ImportValue: ASG
      ScalingAdjustment: -1

  MemoryReservationLowAlert:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Maximum
      Threshold: 35
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
      Period: '60'
      AlarmActions:
      - Ref: SimpleScalingDown
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value:
          Fn::ImportValue: ECScluster
      ComparisonOperator: LessThanThreshold
      MetricName: MemoryReservation

  RequestHighAlert1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Sum
      Threshold: 10
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
      Period: '60'
      AlarmActions:
      - Ref: AutoScalingUp
#      - Ref: AutoScalingDown
      OKActions:
      - Ref: AutoScalingUp
#      - Ref: AutoScalingDown
      Namespace: AWS/ApplicationELB
      Dimensions:
      - Name: LoadBalancer
        Value:
          Fn::ImportValue: LoadBalancerFullName
      ComparisonOperator: GreaterThanOrEqualToThreshold
      MetricName: RequestCount

  RequestHighAlert2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Sum
      Threshold: 100
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
      Period: '60'
      AlarmActions:
      - Ref: AutoScalingUp
      OKActions:
      - Ref: AutoScalingUp
      Namespace: AWS/ApplicationELB
      Dimensions:
      - Name: LoadBalancer
        Value:
          Fn::ImportValue: LoadBalancerFullName
      ComparisonOperator: GreaterThanThreshold
      MetricName: RequestCount

  AutoScalingUp:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ScalingUp
      PolicyType: StepScaling
      ScalingTargetId:
        Fn::ImportValue: ScalableTarget
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 180
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 10
            ScalingAdjustment: -1
          - MetricIntervalLowerBound: 10
            MetricIntervalUpperBound: 100
            ScalingAdjustment: 0
          - MetricIntervalLowerBound: 100
            ScalingAdjustment: 2

#  RequestLowAlert:
#    Type: AWS::CloudWatch::Alarm
#    Properties:
#      EvaluationPeriods: '1'
#      Statistic: Sum
#      Threshold: 10
#      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
#      Period: '60'
#      AlarmActions:
#      - Ref: AutoScalingDown
#      Namespace: AWS/ApplicationELB
#      Dimensions:
#      - Name: LoadBalancer
#        Value:
#          Fn::ImportValue: LoadBalancerFullName
#      ComparisonOperator: LessThanThreshold
#      MetricName: RequestCount
